### ISSUE TITLE
Missing information in decompilation instructions

### ISSUE THREAD

**Issue by TheMCHK** [CHEF-KOCH/HWIDGEN-SRC#1]
There is missing info in the decompiler instructions file under /docs, such as how to extract the binary files from the HWIDGEN EXE. I personally used a UPX unpacker but it would be cool to know how s1ave77 tried to pack the main EXE.

**Comment by CHEF-KOCH** [comment]
You can scan what he used with e.g. [PEID](https://github.com/wolfram77web/app-peid). 

However I already did that and he used several different programs over time. I saw you opened another issue ticket regarding compiling errors. I will definitly look into it as soon as I'm back home and upgrade the instructions.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/HWIDGEN-SRC/commit/d18e6540eeb0feb33fa526bb72966b8273328168

**Comment by TheMCHK** [comment]
> [d18e654](https://github.com/CHEF-KOCH/HWIDGEN-SRC/commit/d18e6540eeb0feb33fa526bb72966b8273328168)

Thanks, but that's not my post. [This is the correct link.](https://www.reddit.com/r/Piracy/comments/d654al/contribution_hwidgen_source_code)
