### ISSUE TITLE
After recompiling from the AHK file, program fails.

### ISSUE THREAD

**Issue by TheMCHK** [CHEF-KOCH/HWIDGEN-SRC#2]
It happens during the initial startup check, it displays an error:

`Error: Failed attempt to launch program or document:
Action: < C:\Windows\sysnative\cmd.exe>
Params: </c (cscript.exe /nologo
C:\Users\[REDACTED]\AppData\Local\Temp\PIDS.vbs) > > C:\Users\[REDACTED]\AppData\Local\Temp\kms.log>`

It can't find that file, but why is it throwing that if the source code is the same anyway?

**Comment by Bewinxed** [comment]
I'm getting the same error on the precompiled file, trying to activate server 2019 datacenter

![image](https://user-images.githubusercontent.com/9145989/67089322-fbf1a800-f1af-11e9-83da-f9c22268327e.png)

**Comment by TheMCHK** [comment]
@CHEF-KOCH any ideas?

**Comment by CHEF-KOCH** [comment]
I did not forgot you, don't worry. I'm working on the solution, but first I have to re-write some KMS activator parts and then I'm going to focus on HWIDGEN a bit more. Sorry.

**Comment by jinraynor1** [comment]
got this erro too, it seems decompiler does not work for some commands, to fix this error edit around line 1452, replace this line:
`RunWait, %system32%\cmd.exe /c (cscript.exe /nologo %A_Temp%\PID8.vbs)>>%A_Temp%\kms.log, `, Hide
with this one
`RunWait, %ComSpec% /c ""cscript.exe" "/nologo" "%A_Temp%\PID8.VBS" >> %A_Temp%\kms.log", , Hide`

 i will try to patch my windows now =)
