### ISSUE TITLE
[Question] Can HWIDGEN be detected by Microsoft in any way shape or form?

### ISSUE THREAD

**Issue by Filo97** [CHEF-KOCH/HWIDGEN-SRC#3]
I'm admittedly worried about consequences of Microsoft finding out

**Comment by CHEF-KOCH** [comment]
Microsoft is already aware of it because I submitted it to them. 

Exclude it in Windows Defender and that's it.

**Comment by Filo97** [comment]
Alright, thanks! Was just a lil worried, afraid of getting my Microsoft account somehow banned, but if they're as lax as you say they are i shouldn't worry then
